### ISSUE TITLE
Add a more elaborate example

### ISSUE THREAD

**Issue by gedw99** [miyoyo/Compass#1]
This looks like it might solve an issue I have.

Could you add an example with many pages routing between each other ?

Also is Virgil dead ? Compass replaces it ?

**Comment by miyoyo** [comment]
Virgil is going to be marked as outdated as soon as the release that supports arguments for named routes hits beta.

**Comment by gedw99** [comment]
Hey @miyoyo 

Makes sense. Thanks.
